### ISSUE TITLE
Reloadium Debug missing in remote PyCharm IDE

### ISSUE THREAD

**Issue by cvrtky** [reloadware/reloadium#93] opened 2023-01-29 22:40 UTC
## Describe the bug*
when working remotely using Pycharm and Gateway (both latest version 2023.3.2), I get reloadium run and relaod file in the remote IDE, but no Reloadium debug

## To Reproduce
Using PyCharm PRo and Gateway, both latest version (2023.3.2) connect to remote IDE using gateway and ssh w. keypairs and install reloadium either form local storrage or from you windows PC.

## Expected behavior
I expeted the Reloadium debugger to be available. It 's not only Rloadium run and reload files shows up

## Screenshots
![Remote PyCharm](https://user-images.githubusercontent.com/15069324/215359717-46f747bd-f9f3-43d9-850f-89f2b88bc604.jpg)

## Desktop or remote (please complete the following information):**
I've tried this on a windows 10 Pro upgraded to Windows 11 Pro. Thsi using a self build shuttle pc i5-9600 w. 16GB RAM

and a fresh installed windows 11 Pro on a Lenovo Yoga 7 anlso w. 16GB RAM

For the remote Linux I tried Debian Bullseye running directly on HW ( Asus ROG mobo w. i5-12400 and 64GB RAM) og
Devuan Chimerea (debian bullseyes without systemd) running in a VM hosted on ESXi 7.0.3 using the above HW

In both cases I don't see the the Reloadium debugger in the remote IDE

**Comment by dkrystki** [comment] 2023-02-27 15:23
I couldn't replicate this since Gateway seems to be not supported for plugin development but this might be related to the new UI issues which was fixed in PyCharm plugin 0.9.6 so please give it a go and let me know.

**Comment by cvrtky** [comment] 2023-03-04 23:33
Sorry for the belated reply.
No upgrading to 0.9.6 doesn't change any thing. I only get Reloadium run in the remote IDE.
I'm using Pycharm 2023.3.2 but also tried on 2023.3.3 EAP. Same thing.
I'm using the classic UI not the new one. I tried the new UI briefly today for the first time. I just took a peek and "Oh my" That looks different" and switched back :D

**Comment by dkrystki** [comment] 2023-04-23 01:15
I'm not able to fix this unfortunately.
JetBrains doesn't seem to provide development setup for Gateway so I'm unable to reproduce it.

**Closed by dkrystki** 2023-04-23 01:15 UTC
Labels: wontfix
