### ISSUE TITLE
C:\Python310\python.exe: No module named reloadium.flask_test

### ISSUE THREAD

**Issue by UtpalDas6** [reloadware/reloadium#13] opened 2022-05-13 19:23 UTC
**Describe the bug**
Trying to run flask hello world app with reloadium gives error.

**To Reproduce**
1. pip install reloadium --user
2. python -m reloadium run .\flask_test.py

**Expected behavior**
Ideally it should start tracking files and reload app based on changes.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/36782722/168375646-dbe6d552-665b-4586-a962-d4607652ce29.JPG)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Reloadium package version: [0.8.7]
 - Editor: [Vscode]
 - Run mode: [Run/Debug]

**Comment by dkrystki** [comment] 2022-05-14 02:11
That seems like a bug. 
Could you try running it with ( example from https://flask.palletsprojects.com/en/2.1.x/quickstart/ ):

```
set FLASK_APP=flask_test
reloadium run -m flask run
```
or
 
```
set FLASK_APP=flask_test
python -m reloadium run -m flask run
```

**Comment by UtpalDas6** [comment] 2022-05-15 08:03
I did but now it shows no module named wsgi and throws an import error
![snap](https://user-images.githubusercontent.com/36782722/168463215-7a38f6e3-54c3-4700-87aa-75555ad55071.png)

**Comment by dkrystki** [comment] 2022-05-15 08:08
That's very strange. What flask version are you using?

**Comment by UtpalDas6** [comment] 2022-05-15 08:18
>>> flask.__version__
'2.0.1'
>>>

**Comment by dkrystki** [comment] 2022-05-15 08:28
I don't think this is Reloadium bug (although the error message might make it look like it, will be fixed).

Does the app run without reloadium?
Can you just simply run `python3 -m pip install wsgi` and check again?

**Comment by UtpalDas6** [comment] 2022-05-15 08:36
I did try that first unfortunately
utpal@utpal-ASUS-Gaming-FX570UD:~/pyStocks$ python3 -m pip install wsgi
ERROR: Could not find a version that satisfies the requirement wsgi (from versions: none)
ERROR: No matching distribution found for wsgi

**Comment by dkrystki** [comment] 2022-05-15 08:42
And what about running without reloadium? Does it throw the error?

**Comment by UtpalDas6** [comment] 2022-05-15 08:48
Without reloadium flask runs fine. I can test individual end points.

**Comment by dkrystki** [comment] 2022-05-15 08:49
Ok I'll deep deeper than.
Do you happen to have a file wsgi.py in your project which you import somewhere?

**Comment by UtpalDas6** [comment] 2022-05-15 10:04
![wsgi](https://user-images.githubusercontent.com/36782722/168467389-edc97a17-9919-486e-9e7b-30521f501eed.png)

**Comment by dkrystki** [comment] 2022-05-15 11:00
Ok I know what is going on. 
The first issue (from the original post) is reloadium issue and will be fixed. 

The second is not really caused by reloadium (but it catches the error before flask which prevents it from printing a nice error - this will be fixed as well).

The problem is that your FLASK_APP env variable is not set.
You have to simply run `export FLASK_APP=server` instead of `set FLASK_APP=server` before running your app

**Comment by UtpalDas6** [comment] 2022-05-15 11:17
Thanks a lot I was using set insted of export on ubuntu 🤣 
![thanks](https://user-images.githubusercontent.com/36782722/168469959-f8aefb09-73d2-4233-a020-1503e200ecb7.png)
will close this

**Closed** 2022-05-15 11:19 UTC
