### ISSUE TITLE
Segmentation fault for python 3.7.3?

### ISSUE THREAD

**Issue by thomas15v** [reloadware/reloadium#28] opened 2022-07-26 15:24 UTC
I know it's a long stretch since it is so old, but if python 3.7.3 loads the cpython it simply gives up:
![image](https://user-images.githubusercontent.com/2163941/181045755-ce602787-65f2-4cdc-9620-9d14d5e23a05.png)

Not sure if there is an easy fix for this? 3.7.9 seems to work, but sadly enough I can't upgrade to it easily. 

I also straced the fault (not sure if helpful):
![image](https://user-images.githubusercontent.com/2163941/181061125-4a2e48ff-f238-4beb-8d49-3730f5b48fb3.png)

**Comment by dkrystki** [comment] 2022-07-27 14:09
Could you try deleting `__pycache__` directories?
Does it happen for debug or run mode?

**Comment by thomas15v** [comment] 2022-07-28 13:54
It happens in both modes. I have already tried to delete several cache directories, with no result. 

Even with a fresh docker container it has the same behaviour:
![image](https://user-images.githubusercontent.com/2163941/181522639-5d7dcb21-5847-428a-be7e-0e7bd6da1b16.png)

**Comment by dkrystki** [comment] 2022-08-09 07:13
Possibly fixed in reloadium 0.9.1 (can't reproduce on python 3.7.3 from pyenv). 
Could you confirm it's working for you as well?

**Closed** 2022-09-05 15:12 UTC
